[2023-07-06 00:07:50,827] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:52,219] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:52,326] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:54,672] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:54,808] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:57,130] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:57,273] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:07:59,643] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:10,138] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:10,266] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:13,588] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:13,723] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:16,053] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:16,178] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:19,523] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:19,642] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:20,953] INFO _log() L224   * Detected change in 'C:\\P\\Izabucks\\Izabucks\\api\\app.py', reloading - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:21,094] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:41,442] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.26:5000 (Press CTRL+C to quit) - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:41,444] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:44,938] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:44] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:45,137] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:45] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:45,153] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:45] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:45,156] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:45] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:45,427] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:45] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:45,436] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:45] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:52,057] WARNING add_bebida() L53   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L53  
[2023-07-06 00:08:52,060] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:52] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 409 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:08:56,877] WARNING add_bebida() L53   Erro ao adicionar bebida 'Pink Drink', Bebida de mesmo nome já salvo na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L53  
[2023-07-06 00:08:56,878] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:08:56] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 409 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:09:33,569] WARNING add_bebida() L57   Erro ao adicionar uma nova bebida 'outro ', Não foi possível salvar uma nova bebida no cardapio :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L57  
[2023-07-06 00:09:33,571] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:09:33] "[31m[1mPOST /bebida/adicionar HTTP/1.1[0m" 400 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:10:25,876] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:10:25] "DELETE /bebida/deletar?id=1&nome=Pink%20Drink HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:10:44,069] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:10:44] "DELETE /bebida/deletar?id=4&nome=Cafe HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:11:05,361] ERROR log_exception() L1449 Exception on /bebida/listas [GET] - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\app.py", line 98, in get_bebidas
    return apresenta_bebida(bebida), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 57, in apresenta_bebida
    result.append(apresenta_bebida(bebida))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\Izabucks\Izabucks\api\schemas\bebida.py", line 56, in apresenta_bebida
    for bebida in bebidas:
TypeError: 'Bebida' object is not iterable
[2023-07-06 00:11:05,370] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:11:05] "[35m[1mGET /bebida/listas HTTP/1.1[0m" 500 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:11:10,529] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:11:10] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:11:10,558] INFO _log() L224  127.0.0.1 - - [06/Jul/2023 00:11:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-06 00:11:33,109] WARNING get_bebida() L74   Erro ao buscar produto '1', Bebida não encontrado na base :/ - call_trace=C:\P\Izabucks\Izabucks\api\app.py L74  
[2023-07-06 00:14:20,973] INFO _log() L224   * Restarting with stat - call_trace=C:\P\Izabucks\Izabucks\api\env\Lib\site-packages\werkzeug\_internal.py L224 
